//
// Created by robot1 on 7/2/24.
//

#ifndef ROBOTVEHICLE_PACKAGE_CONFIGURATIONS_H
#define ROBOTVEHICLE_PACKAGE_CONFIGURATIONS_H

// GridMap and PathPlanning
#define CONFIG_GRID_ROW_SIZE 250
#define CONFIG_GRID_COL_SIZE 250
#define CONFIG_MAX_NUMBER_OF_LINE_POINTS 500
#define CONFIG_DISTANCE_BETWEEN_POINTS_CM 1
#define CONFIG_GRID_VALUE_FULL_OCCUPIED 0
#define CONFIG_GRID_VALUE_FULL_AVAILABLE 1
#define CONFIG_GRID_VALUE_UPDATE_INTERVAL 0.5

#endif //ROBOTVEHICLE_PACKAGE_CONFIGURATIONS_H
