//
// Created by robot1 on 7/2/24.
//

#ifndef ROBOTVEHICLE_PACKAGE_PATHPLANNINGCONSTANTS_H
#define ROBOTVEHICLE_PACKAGE_PATHPLANNINGCONSTANTS_H

#define GRID_ROW_SIZE 250
#define GRID_COL_SIZE 250

#endif //ROBOTVEHICLE_PACKAGE_PATHPLANNINGCONSTANTS_H
