#ifndef SRC_JOYSTICKPARAMS_H_
#define SRC_JOYSTICKPARAMS_H_


#define JOYSTICK_ANALOG_RESOLUTION_BIT 16
#define JOYSTICK_MIN_VOLTAGE 0
#define JOYSTICK_MAX_VOLTAGE 4

#endif /* SRC_JOYSTICKPARAMS_H_ */

