/*
 * VehiclePins.h
 *
 *  Created on: Aug 18, 2022
 *      Author: robot1
 */

#ifndef SRC_VEHICLEPINS_H_
#define SRC_VEHICLEPINS_H_

#define VEHICLE_PIN_QUADRAENCODER_LEFT_CHANNEL_A  31
#define VEHICLE_PIN_QUADRAENCODER_LEFT_CHANNEL_B  32
#define VEHICLE_PIN_QUADRAENCODER_RIGHT_CHANNEL_A 22
#define VEHICLE_PIN_QUADRAENCODER_RIGHT_CHANNEL_B 23

#define VEHICLE_PIN_MOTOR_DRIVER_LEFT_D2 35
#define VEHICLE_PIN_MOTOR_DRIVER_LEFT_IN1 36
#define VEHICLE_PIN_MOTOR_DRIVER_LEFT_IN2 37

#define VEHICLE_PIN_MOTOR_DRIVER_RIGHT_D2 2
#define VEHICLE_PIN_MOTOR_DRIVER_RIGHT_IN1 3
#define VEHICLE_PIN_MOTOR_DRIVER_RIGHT_IN2 4

#endif /* SRC_VEHICLEPINS_H_ */
