/*
 * VehiclePins.h
 *
 *  Created on: Aug 18, 2022
 *      Author: robot1
 */

#ifndef SRC_VEHICLEPINS_H_
#define SRC_VEHICLEPINS_H_

#define VEHICLE_PIN_QUADRAENCODER_LEFT_CHANNEL_A  31
#define VEHICLE_PIN_QUADRAENCODER_LEFT_CHANNEL_B  32
#define VEHICLE_PIN_QUADRAENCODER_RIGHT_CHANNEL_A 22
#define VEHICLE_PIN_QUADRAENCODER_RIGHT_CHANNEL_B 23

// motor 1 / left
#define VEHICLE_PIN_MOTOR_DRIVER_LEFT_PWM 12
#define VEHICLE_PIN_MOTOR_DRIVER_LEFT_INA 27
#define VEHICLE_PIN_MOTOR_DRIVER_LEFT_INB 26
#define VEHICLE_PIN_MOTOR_DRIVER_LEFT_FB 25

// motor 2 / right
#define VEHICLE_PIN_MOTOR_DRIVER_RIGHT_PWM 14
#define VEHICLE_PIN_MOTOR_DRIVER_RIGHT_INA 17
#define VEHICLE_PIN_MOTOR_DRIVER_RIGHT_INB 16
#define VEHICLE_PIN_MOTOR_DRIVER_RIGHT_FB 15

#endif /* SRC_VEHICLEPINS_H_ */

