/*
 * VehicleParameters.h
 *
 *  Created on: Sep 7, 2022
 *      Author: robot1
 */

#ifndef SRC_VEHICLEPARAMETERS_H_
#define SRC_VEHICLEPARAMETERS_H_

// Motor parameters
#define VEHICLE_MOTOR_DRIVER_PWM_FREQUENCY 187500
#define VEHICLE_MOTOR_DRIVER_PWM_RESOLUTION 16
#define VEHICLE_MOTOR_DRIVER_CURRENT_MILLIVOLT_PR_AMP 525

// Quadrature Encoder parameters
#define VEHICLE_MOTOR_ENCODER_COUNT_PR_REV 9600


// general
#define VEHICLE_WHEEL_RADIUS_CM 9
#define VEHICLE_MIMIMUM_CURRENT_DRAW_MILLI_AMP 10

#endif /* SRC_VEHICLEPARAMETERS_H_ */
