/*
 * VehicleParameters.h
 *
 *  Created on: Sep 7, 2022
 *      Author: robot1
 */

#ifndef SRC_VEHICLEPARAMETERS_H_
#define SRC_VEHICLEPARAMETERS_H_

// Motor parameters
#define VEHICLE_MOTOR_DRIVER_PWM_FREQUENCY 187500
#define VEHICLE_MOTOR_DRIVER_PWM_RESOLUTION 16
#define VEHICLE_MOTOR_DRIVER_CURRENT_MILLIVOLT_PR_AMP 525


// Quadrature Encoder parameters
//#define VEHICLE_MOTOR_ENCODER_COUNT_PR_REV 9600
#define VEHICLE_MOTOR_ENCODER_COUNT_PR_REV 3200


// general
#define VEHICLE_WHEEL_RADIUS_CM 9
#define VEHICLE_MIMIMUM_CURRENT_DRAW_MILLI_AMP 10

// PI controller coeffiences
#define VEHICLE_PI_CONTROL_COEFFICIENT_B0 206
#define VEHICLE_PI_CONTROL_COEFFICIENT_B1 -90
#define VEHICLE_PI_CONTROL_COEFFICIENT_A1 -1

// encoder filter
#define VEHICLE_TRANPOSED_IIR_FILTER_SENSOR_B0  0.0591907
#define VEHICLE_TRANPOSED_IIR_FILTER_SENSOR_B1  0.0591907
#define VEHICLE_TRANPOSED_IIR_FILTER_SENSOR_A1  -0.88161859

// sample timer
#define VEHICLE_SAMPLE_TIMER_INTERVAL_MICROS 100

#endif /* SRC_VEHICLEPARAMETERS_H_ */
