name: Build and Push ROS2 Humble Base Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g. latest, v1.0.0)'
        required: true
        default: 'latest'

jobs:
  build-and-push-humble-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build ROS2 Humble base Docker image
        run: docker build -t ros2_humble_image -f Docker/humble/Dockerfile .

      - name: Tag Docker image for GitHub Container Registry
        run: docker tag ros2_humble_image ghcr.io/${{ github.actor }}/ros2_humble_image:${{ github.event.inputs.image_tag }}

      - name: Push ROS2 Humble base Docker image
        run: docker push ghcr.io/${{ github.actor }}/ros2_humble_image:${{ github.event.inputs.image_tag }}

      - run: echo "✅ Image pushed to ghcr.io/${{ github.actor }}/ros2_humble_image:${{ github.event.inputs.image_tag }}"
